name: Race Detection Tests
on:
  push:
    branches:
      - main
  pull_request: {}
jobs:
  race-tests:
    runs-on:
      group: Ampersand Private
    steps:
      # Predefined action from marketplace. Clones the source code.
      - uses: actions/checkout@v5

      # Predefined action from marketplace. Installs go on the system.
      - name: Set up go
        uses: actions/setup-go@v6
        with:
          go-version: "1.24.6"

      # Run go generate
      - name: Generate
        run: go generate ./...

      # Run tests with race detector
      - name: Race Detection Tests
        env:
          SKIP_FLAKY_TESTS: "true"
          RUNNING_ENV: "test"
        run: go test -race -v $(go list ./... | grep -v scripts/)
