name: Unit Tests
on:
  push:
    branches:
      - main
  pull_request: {}
jobs:
  build:
    runs-on:
      group: Ampersand Private
    steps:
      # Predefined action from marketplace. Clones the source code.
      - uses: actions/checkout@v5

      # Predefined action from marketplace. Installs go on the system.
      - name: Set up go
        uses: actions/setup-go@v6
        with:
          go-version: "1.24.6"

      # Run go generate
      - name: Generate
        run: go generate ./...
      # Run tests
      - name: Unit Tests
        env:
          SKIP_FLAKY_TESTS: "true"
          RUNNING_ENV: "test"
        run: go test -v $(go list ./... | grep -v scripts/) -coverprofile=./cover.out -covermode=atomic -coverpkg=./...
      - name: Coverage Check
        uses: vladopajic/go-test-coverage@v2
        with:
          config: ./.testcoverage.yml
          profile: cover.out
          local-prefix: github.com/amp-labs/server
          threshold-file: 0
          threshold-package: 0
          threshold-total: 0
