name: Unit Tests
on:
  push:
    branches:
      - main
  pull_request: {}
jobs:
  build:
    runs-on:
      group: Ampersand Private
    steps:
      # Predefined action from marketplace. Clones the source code.
      - uses: actions/checkout@v5

      # Predefined action from marketplace. Installs go on the system.
      - name: Set up go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      # Run go generate
      - name: Generate
        run: go generate ./...
      # Run tests
      - name: Unit Tests
        env:
          SKIP_FLAKY_TESTS: "true"
          RUNNING_ENV: "test"
        run: go test -json $(go list ./... | grep -v scripts/) -coverprofile=./cover.out -covermode=atomic -coverpkg=./... | tee results.json
      - name: Generate coverage results
        run: go tool cover -func=cover.out -o=coverage.func.out
      - name: Render Test Summary
        uses: robherley/go-test-action@v0
        with:
          fromJSONFile: results.json

      - name: Go Coverage Badge  # Pass the `cover.out` output to this action
        uses: tj-actions/coverage-badge-go@v3
        with:
          filename: cover.out

      - name: Verify Changed files
        uses: tj-actions/verify-changed-files@v16
        id: verify-changed-files
        with:
          files: README.md

      - name: Coverage Check
        uses: vladopajic/go-test-coverage@v2
        with:
          config: ./.testcoverage.yml
          profile: cover.out
          local-prefix: github.com/amp-labs/server
          threshold-file: 0
          threshold-package: 0
          threshold-total: 0

      - name: Commit changes
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "auto: Updated coverage badge."

      - name: Push changes
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ github.token }}
          branch: ${{ github.head_ref }}
